name: Generate Trophy

on:
  schedule:
    - cron: "45 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate trophy
        uses: ryo-ma/github-profile-trophy@ccb591b887775ee567c0d9a38424ddfb9b1906c4 # master, includes theme input
        with:
          username: Mugweru01
          output_path: ./profile-trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          theme: algolia

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add profile-trophy.svg
          git commit -m "Update trophy" || exit 0
          git push
